export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const GET_SERVICE = 'GET_SERVICE';
export const FILL_SERVICE_FIELD = 'FILL_SERVICE_FIELD';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const RESET_SERVICE_FIELD = 'RESET_SERVICE_FIELD';


